# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  - group: ServicesHubMobile

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - task: DownloadSecureFile@1
    displayName: 'Download app insights key'
    name: appinsightskey
    inputs:
      secureFile: app-insights-key.json
      
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'android/gradlew'
      workingDirectory: 'android'
      tasks: 'assembleDevRelease'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/android/app/build/outputs/apk/dev/release'
      Contents: '*.apk'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'DevOpsDev'
      publishLocation: 'Container'
